name: Skyline Token Workflow

on:
  pull_request:
    types: [opened]

jobs:
  skyline-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get Skyline access token
        id: get_token
        run: |
          response=$(curl -s -X POST https://api.skyline.be/Token \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "username=${{ secrets.SKYLINE_USERNAME }}" \
            -d "password=${{ secrets.SKYLINE_PASSWORD }}" \
            -d "grant_type=password")
          echo "API response: $response"
          token=$(echo "$response" | jq -r '.access_token')
          if [ "$token" == "null" ] || [ -z "$token" ]; then
            echo "Failed to retrieve access token"
            exit 1
          fi
          echo "token=$token" >> $GITHUB_OUTPUT

      - name: Post PR Details
        uses: actions/github-script@v7
        env:
          SKYLINE_TOKEN: ${{ steps.get_token.outputs.token }}
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = `[PR#${pr.number}] ${pr.title}`;
            const fullTitle = title;
            const author = pr.user.login;
            const commitMessage = pr.body || "No PR body provided.";
            const prUrl = pr.html_url;

            // Get files changed
            const files = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
            const changedFiles = files.data.map(f => `- \`${f.filename}\``).join('\n');

            const description = `### Pull Request Details
- **Author**: ${author}
- **Commit Message**: ${commitMessage}
- **Files Changed**:
${changedFiles}
- **PR URL**: ${prUrl}`;

            const payload = {
              Title: title,
              Type: "Issue",
              Category: "DIS",
              Customer: { ID: "40" },
              Project: { ID: "16457" },
              Status: "Code Review",
              Assignee: { ID: "5121" },
              Description: description,
              FullTitle: fullTitle,
              Labels: [{ ID: "7095" }],
              Creator: { ID: "5121" }
            };

            const response = await fetch("https://your.api.endpoint/issue", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${process.env.SKYLINE_TOKEN}`
              },
              body: JSON.stringify(payload)
            });

            if (!response.ok) {
              const text = await response.text();
              core.setFailed(`HTTP POST failed: ${response.status} - ${text}`);
            } else {
              core.info("PR details successfully posted.");
            }
