name: Skyline Token Workflow

on:
  pull_request:
    types: [opened]

jobs:
  skyline-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Get Skyline access token
        id: get_token
        run: |
          response=$(curl -s -X POST https://api.skyline.be/Token \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "username=${{ secrets.SKYLINE_USERNAME }}" \
            -d "password=${{ secrets.SKYLINE_PASSWORD }}" \
            -d "grant_type=password")

          echo "API response: $response"

          token=$(echo "$response" | jq -r '.access_token')
          if [ "$token" == "null" ] || [ -z "$token" ]; then
            echo "Failed to retrieve access token"
            exit 1
          fi

          echo "access_token=$token" >> $GITHUB_OUTPUT

      # - name: Use Skyline token in API request
      #   run: |
      #     curl -X POST https://api.skyline.be/some-protected-resource \
      #       -H "Authorization: Bearer ${{ steps.get_token.outputs.access_token }}" \
      #       -H "Content-Type: application/json" \
      #       -d '{"data": "example"}'
